spring:
  application:
    name: todo-service

  datasource:
    url: jdbc:postgresql://localhost:5432/todo
#    username: todo_user
#    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000           # 30 sec idle timeout
      max-lifetime: 1800000         # 30 min max lifetime
      connection-timeout: 20000     # 20 sec connection wait
      leak-detection-threshold: 30000  # Set only for diagnosing issues; remove in prod
      validation-timeout: 5000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false        # Disable Open Session in View for cleaner architecture
    hibernate:
      ddl-auto: update       # Strict mode: validate schema, don’t auto-create
    show-sql: false            # Disable in prod, can override in dev
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
        order_inserts: true
        order_updates: true
        batch_size: 1000         # Enable batching for performance
        generate_statistics: false
  sql:
    init:
      mode: never

  jackson:
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080
  servlet:
    context-path: /todo-service

logging:
  level:
    root: INFO
    com.prod.todo: DEBUG
